name: cla-check

on: [pull_request]

jobs:
  cla-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check if CLA signed
        uses: chris-peterson444/has-signed-canonical-cla@empty-email-not-okay
