name: cla-check

on: [pull_request]

jobs:
  cla-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@d8942819445fb93015c6f298e1636a23f6f47064
